export function getDisplayName(username: string | null, wallet: string): string {
  const looksAutoGenerated = username && /^0x[a-fA-F0-9]{20,}-\d+$/.test(username);
  if (!username || looksAutoGenerated) {
    return truncateWallet(wallet);
  }
  return username;
}

export function truncateWallet(wallet: string): string {
  if (wallet.length <= 16) return wallet;
  return `${wallet.slice(0, 8)}...${wallet.slice(-6)}`;
}

export function polymarketProfileUrl(wallet: string): string {
  return `https://polymarket.com/profile/${wallet}`;
}

export function marketSourceUrl(source: string, externalId: string, slug: string | null): string | null {
  if (source === "polymarket") {
    return slug ? `https://polymarket.com/event/${slug}` : null;
  }
  return null;
}